spring:
  datasource:
    url: jdbc:sqlserver://azure-training-database-server.database.windows.net:1433;database=Training-database;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
    username: sharad-azure-training
    password: nagarro@123
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect : org.hibernate.dialect.SQLServer2012Dialect
      
server:
  port: 8088